### ISSUE TITLE
I don't understand how it work

### ISSUE THREAD

**Issue by luca-vercelli** [BmanDesignsCanada/Lir#1]
I have set it up, and I have tried to use, but actually the command I gave is not executed and I get an error I cannot understand.

![schermata del 2015-12-16 13 16 06](https://cloud.githubusercontent.com/assets/9864296/11840586/43f185ae-a3f7-11e5-8a22-5dd2fdf774d7.png)

**Comment by BrettMayson** [comment]
I haven't moved all the commands of to Lir yet. That's why these two don't work.

**Comment by luca-vercelli** [comment]
Ok probably I got it. I have uploaded some more commands.
I cannot see how you're planning to distinguish english/fr/it/... files

**Comment by BrettMayson** [comment]
I accidentally skipped that, I already know how I am going to fix it. I am in the middle of exams right now and starting a new job. I will start working on this project a lot more in a few weeks.

**Comment by BrettMayson** [comment]
Closing as the language problem was solved.
