### ISSUE TITLE
Still trying to understand

### ISSUE THREAD

**Issue by luca-vercelli** [BmanDesignsCanada/Lir#3]
Hello,
I am still trying to understand how Lir works. I see that most plugins have no "actions". What does it mean? It's just that they are not here /yet/? Can I help you some way?

**Comment by BrettMayson** [comment]
Lir is going to be used for more than speech, although speech is a major part. The plugins with out actions are for other purposes. I am going to release in a few days here an android app that will pair with lir and be able to control the computer as well as request information (currently playing song as well as album art, download files to your device, upload files, mirror notification); Stuff that the user can't do with their voice.
