### ISSUE TITLE
Hi i tried to install but im having problems i assume probably because your not done yet 

### ISSUE THREAD

**Issue by affordablewindurbines** [BmanDesignsCanada/Lir#4]
Hi i tried to install but im having problems i assume probably because your not done yet , so im patiently waiting release, thanks

**Comment by BrettMayson** [comment]
It should install properly. Please post all the output.

**Comment by affordablewindurbines** [comment]
okay heres the output
john@jarvis-quadcore:~/Lir-master$ '/home/john/Lir-master/wizard' 
Installing Lir Python Module
[sudo] password for john: 
Traceback (most recent call last):
  File "/home/john/Lir-master/wizard", line 287, in <module>
    main()
  File "/home/john/Lir-master/wizard", line 282, in main
    wizard = SetupWizard()
  File "/home/john/Lir-master/wizard", line 156, in **init**
    self.builder.add_from_file("interface/setup.glade")
gi._glib.GError: interface/setup.glade: required gtk+ version 3.12, current version is 3.10

**Comment by affordablewindurbines** [comment]
i tried to upgrade to  gtk+ version 3.12 but cant ?

**Comment by BrettMayson** [comment]
What operating system?

**Comment by BrettMayson** [comment]
I have lowered the requirement to 3.10. If you pull and try again it should work.

**Comment by affordablewindurbines** [comment]
ok

On Thu, Feb 18, 2016 at 1:09 PM, Brett Mayson notifications@github.com
wrote:

> I have lowered the requirement to 3.10. If you pull and try again it
> should work.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BmanDesignsCanada/Lir/issues/4#issuecomment-185866398
> .

## 

Affordable Wind Turbines http://www.affordablewindturbines.org
affordablewindturbines.org http://www.affordablewindturbines.org
http://www.facebook.com/affordable.turbines_Company Name_ Affordable Wind
Turbines

Phone number    361-444-3711
529 Clifford St.
City,State, 78404 Corpus Christi Texas
E-mail address affordablewindturbines@gmail.com

[image: --]

Intercepting Altering Or Reading this e-mail by any unauthorized user is a
federal crime under the Electronic Communications Protection Act (ECPA) (18
U.S.C.A 2517(4))

**Comment by affordablewindurbines** [comment]
thank worked it runs the install gui now thanks
